# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_hash_string <- function(x) {
    .Call(`_rmake_cpp_hash_string`, x)
}

cpp_extract_fun <- function(R_str, R_fun_str) {
    .Call(`_rmake_cpp_extract_fun`, R_str, R_fun_str)
}

cpp_clean_comments <- function(R_str) {
    .Call(`_rmake_cpp_clean_comments`, R_str)
}

cpp_valid_code_index <- function(R_str) {
    .Call(`_rmake_cpp_valid_code_index`, R_str)
}

cpp_absolute_to_relative <- function(R_paths, R_root) {
    .Call(`_rmake_cpp_absolute_to_relative`, R_paths, R_root)
}

cpp_create_chunks <- function(R_path) {
    .Call(`_rmake_cpp_create_chunks`, R_path)
}

